### PR TITLE
Fix docker hub release

### LINKED ISSUE #27: Nim v1.2.2
Hi @moigagoo,

Seems that the build fail at https://travis-ci.com/github/moigagoo/nimage/jobs/350968398, and then docker hub has not been updated.

Regards,

-------
Related to https://github.com/the-benchmarker/web-frameworks/pull/2989

### PR DESCRIPTION
**Pull request by waghanza**
Hi @moigagoo,

This `PR` skip file cleanup in `CI` as noticed in https://travis-ci.com/github/moigagoo/nimage/jobs/350968398#L290

More info at https://docs.travis-ci.com/user/deployment#uploading-files-and-skip_cleanup

Regards,

------------------------------
Closes #27

### CODE REVIEW

**Comment by waghanza** [comment]
Why closed ?

**Comment by moigagoo** [comment]
Hmmm, I can swear I merged it, not closed it 🤔

**Comment by waghanza** [comment]
Strange, then ... UI display a closing message

Btw, thanks :tada:

**Comment by moigagoo** [comment]
Oh, apparently, you can't merge from phone 😒

**Comment by moigagoo** [comment]
Merged! Thank you! 🙏

**Comment by waghanza** [comment]
I think you need to integrate this into the `1.2.2` **tag** to deploy on docker hub

**Comment by moigagoo** [comment]
I'm afk right now, will do that later.

Sent from Outlook Mobile<https://aka.ms/blhgte>

________________________________

**Comment by waghanza** [comment]
sure, better not to hurry

**Comment by moigagoo** [comment]
I'll just add the new build to Docker hub manually since I don't want to modify the already existing 1.2.2 tag.

However, when the next Nim version is released, we'll be able to see if your fix works.

Thanks again!

**Pull request merged**
